# Generated by Django 6.0.5 on 2026-07-17 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('proposal_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('submission', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('reviewer_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('student', 'Student'), ('lecturer', 'Lecturer'), ('admin', 'Admin')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('approval_id', models.AutoField(primary_key=True, serialize=False)),
                ('approved_by', models.CharField(max_length=255)),
                ('approval_date', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('proposal', models.ForeignKey(db_column='proposal_id', on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='pop_system.proposal')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('comments', models.TextField(blank=True, null=True)),
                ('score', models.PositiveSmallIntegerField()),
                ('review_date', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.ForeignKey(db_column='proposal_id', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='pop_system.proposal')),
                ('reviewer', models.ForeignKey(db_column='reviewer_id', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='pop_system.reviewer')),
            ],
        ),
        migrations.AddField(
            model_name='proposal',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='pop_system.user'),
        ),
    ]
